require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/units", type: :request do
  before(:each) do
    auth_headers = { "ACCEPT" => "application/vnd.api+json", "CONTENT_TYPE" => "application/vnd.api+json"}
    post auths_url, headers: auth_headers
    token_request = JSON.parse(response.body)
    @token = token_request["token"]
  end

  # This should return the minimal set of attributes required to create a valid
  # Unit. As you add validations to Unit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { 
      name: "Duzia" 
    }
  }

  let(:invalid_attributes) {
    { 
      name: ""
    }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # UnitsController, or in your router and rack
  # middleware. Be sure to keep this updated too.

  let(:valid_headers) {
    {
      "ACCEPT" => "application/vnd.api+json",
      "CONTENT_TYPE" => "application/vnd.api+json",
      "AUTHORIZATION" => "Bearer #{@token}"
    }
  }

  describe "GET /index" do
    it "renders a successful response" do
      get units_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      unit = Unit.create!(:name => "Combo")
      get unit_url(unit), headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Unit" do
        expect {
          post units_url,
               params: { unit: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Unit, :count).by(1)
      end

      it "renders a JSON response with the new unit" do
        post units_url,
             params: { unit: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/vnd.api+json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Unit" do
        expect {
          post units_url,
               params: { unit: invalid_attributes }, as: :json
        }.to change(Unit, :count).by(0)
      end

      it "renders a JSON response with errors for the new unit" do
        post units_url,
             params: { unit: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/vnd.api+json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          name: "Combo"
        }
      }

      it "updates the requested unit" do
        unit = Unit.create! valid_attributes
        patch unit_url(unit),
              params: { unit: new_attributes }, headers: valid_headers, as: :json
        unit.reload
      end

      it "renders a JSON response with the unit" do
        unit = Unit.create! valid_attributes
        patch unit_url(unit),
              params: { unit: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/vnd.api+json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the unit" do
        unit = Unit.create! valid_attributes
        patch unit_url(unit),
              params: { unit: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/vnd.api+json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested unit" do
      unit = Unit.create! valid_attributes
      expect {
        delete unit_url(unit), headers: valid_headers, as: :json
      }.to change(Unit, :count).by(-1)
    end
  end
end
